### ISSUE TITLE
Scroll to next panel after completing a field

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikestart#6]
This is the unfocused state; it would be a bit transparent:
<img width="148" alt="screenshot 2017-06-27 14 28 42" src="https://user-images.githubusercontent.com/376315/27589928-f7a2b5b8-5b44-11e7-9776-52701b0f1348.png">

...when the user scrolls down to (or is scrolled down to) a panel, the first input in that panel acquires focus and a greyed out "done" or "next" (not sure which yet) button appears:
<img width="151" alt="screenshot 2017-06-27 14 28 07" src="https://user-images.githubusercontent.com/376315/27589927-f7a05f84-5b44-11e7-8e0b-fe733102ea32.png">

...once they've completed the field to our validation rules' satisfaction (so probably "there is a character in there, at least for now), the button becomes active:
<img width="154" alt="screenshot 2017-06-27 14 28 35" src="https://user-images.githubusercontent.com/376315/27589929-f7a3ccdc-5b44-11e7-9775-5d7601d61a7e.png">

...once they click that button, we scroll them down to the next panel using a smooth-scroll like this: http://iamdustan.com/smoothscroll/

Typeform does this reallllllllly nicely: https://www.typeform.com/examples/#insight

If we could get something similar to that behaviour happening here, I think it'd make the form much more pleasant to use and reduce the cognitive load of making lots of little decisions (see [this article](https://www.smashingmagazine.com/2017/05/better-form-design-one-thing-per-page/) for rationale.)

**Comment by sarahmonster** [comment]
Just a quick drive-by comment here about the `onchange` event in React, which behaves a bit unexpectedly: if you use `onchange`, the listener will fire every time a character is added or removed from the input (ie, every letter typed fires the event), but `onblur` only fires once focus is removed from the input.

So, for this behaviour, we'd probably want to use `onchange`, but for setting state, we may only want to do that `onblur`. I don't know if that's helpful at all, I just happened to be testing something else and noticed the behaviour and thought it might be useful (@danielwrobert you mentioned this I think?)

https://www.peterbe.com/plog/onchange-in-reactjs

**Comment by danielwrobert** [comment]
Yes, we talked about this a little bit when we were discussing showing the "next step" buttons. Glad you noted this here though because I forgot about the idea switching the state change to `onblur`.

**Comment by sarahmonster** [comment]
This might be helpful here: https://codepen.io/brian-baum/pen/mJZxJX

**Comment by danielwrobert** [comment]
That could work - it is animating the scrolling with timeouts ... I _guess_ that might be similar to what another library would do (?) but I feel like transitions might work better.

Anyhow, [here is the resource I mentioned](https://codedaily.io/tutorials/8/Build-a-Reusable-Scroll-List-Component-with-Animated-scrollTo-in-React). It uses [scroll-into-view](https://github.com/KoryNunn/scroll-into-view), which is why I mentioned it might be doing the timeout thing under the hood (I haven't looked).

It seems like it wouldn't be too difficult to implement but we may not want/need to use the whole outer container section, just the inside `scrollTo` bit.
